services:
  - name: my-golang-app
    type: web
    env: go
    plan: free
    buildCommand: |
      ng build --configuration=production
      cd server
      go mod tidy
    startCommand: ./server
    envVars:
      - key: DATABASE_URL
        sync: false
